# Generated by Django 6.0.3 on 2026-04-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False)),
                ('can_read_all', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_update_all', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_delete_all', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.businesselement')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.role')),
            ],
            options={
                'unique_together': {('role', 'element')},
            },
        ),
    ]
